spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/Dev/h2database/sinaling-server
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
